name: Deploy to Heroku # Name of the GitHub Action

on:
  push: # Action triggering the GitHub Action...
    branches: # ... on the branch specified below
      - main # <- MODIFY branch name (e.g. "dev")

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # <- MODIFY Heroku app name
          heroku_app_name: "ob-zeng" # <- MODIFY Heroku app name
          heroku_email: "olivier@olivierbattini.fr" # <- MODIFY Heroku account email
